version: '3.8'

services:
  backend:
    build: ./backend
    env_file:
      - ./env
    expose:
      - "3000"

  caddy:
    image: caddy
    restart: unless-stopped
    ports:
      - 80:80
      - 443:443
      - 443:443/udp
    volumes:
      - ./Caddyfile:/etc/caddy/Caddyfile
      - ./frontend:/srv
      - caddy_data:/data
      - caddy_config:/config

volumes:
  caddy_data:
  caddy_config:
